version: 2.1
orbs:
  android: circleci/android@2.2.0
  flutter: circleci/flutter@2.0.1
  slack: circleci/slack@4.12.1
jobs:
  distribute:
    executor:
      name: android/android-docker
      tag: 2023.04.1
    steps:
      - flutter/install_sdk_and_pub:
          version: 3.7.11
      - flutter/install_android_gradle_dependencies
      - flutter/install_android_gem
      - checkout
      - run:
          name: Build Binaries
          command: flutter pub get;flutter build apk --build-name="1.0.0" --build-number=${CIRCLE_BUILD_NUM} --release;mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/FlutterTemplate-release-${CIRCLE_BUILD_NUM}.apk
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
      - store_artifacts:
          path: build/app/outputs/flutter-apk
          destination: apk
workflows:
  distribute:
    jobs:
      - distribute