version: 2.1
orbs:
  flutter: circleci/flutter@2.0.1
  slack: circleci/slack@4.12.1
jobs:
  android-deployment:
    docker:
      - image: cimg/android:2023.04
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 3.7.11
      - flutter/install_android_gradle
      - flutter/install_android_gemㅇ
      - run:
          name: Build Binaries
          command: flutter pub get;flutter build apk --build-name="1.0.0" --build-number=${CIRCLE_BUILD_NUM} --release;mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/FlutterTemplate-release-${CIRCLE_BUILD_NUM}.apk
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
      - store_artifacts:
          path: build/app/outputs/flutter-apk
          destination: apk
workflows:
  deployment:
    jobs:
      - build-approval:
          type: approval
      - android-deployment:
          requires:
            - build-approval
